[hekad]
base_dir="base_heka"
share_dir="share_heka"

[tcp:4242]
type = "TcollectorInput"
address = "localhost:4242"
decoder = "tsd_decoder"

[tsd_decoder]
type="OpenTsdbRawDecoder"

[tsd_encoder]
type = "OpenTsdbRawEncoder"

[zabbix_encoder]
type = "ZabbixEncoder"

[OpentsdbZabbixFilter]
strip_tags = [ "product", "cluster", "class" ]
message_matcher = "Type == 'opentsdb'"

  [OpentsdbZabbixFilter.replace]
  / = "_"

  [OpentsdbZabbixFilter.replace_tag_name]
  class_name = "cn-"
  exception_class = "ec-"
  method_signature = "ms-"

[opentsd]
type = "TcpOutput"
address = "127.0.0.1:4243"
encoder = "tsd_encoder"
message_matcher = "Type == 'opentsdb'"

[zabbix]
type = "ZabbixOutput"
ticker_interval = 5
send_key_count = 1000
max_key_count = 2000
receive_timeout = 1000
#address = "zabbix.tm.tmcs:10051"
#address = "192.168.56.101:10051"
address = "localhost:10051"
zabbix_active_check_filtering=false
zabbix_checks_poll_interval=300
encoder = "zabbix_encoder"
override_hostname= "testhost"
message_matcher = "Type == 'zabbix'"
