[hekad]
base_dir="base_heka"
share_dir="share_heka"

[tcp:4242]
type = "TcollectorInput"
address = "localhost:4242"
decoder = "tsd_decoder"

[tsd_decoder]
type="OpenTsdbRawDecoder"

[tsd_encoder]
type = "OpenTsdbRawEncoder"

[zabbix_encoder]
type = "ZabbixEncoder"

[OpentsdbZabbixFilter]
message_matcher = "Type == 'opentsdb'"

[opentsd]
type = "TcpOutput"
address = "127.0.0.1:4243"
encoder = "tsd_encoder"
message_matcher = "Type == 'opentsdb'"

[zabbix]
type = "ZabbixOutput"
ticker_interval = 5
send_key_count = 3
max_key_count = 10
receive_timeout = 500
#address = "zabbix.tm.tmcs:10051"
address = "192.168.56.101:10051"
zabbix_checks_poll_interval=10
encoder = "zabbix_encoder"
override_hostname= "testhost"
#override_hostname= "mgr1.mf.ams2.coresys.tmcs"
message_matcher = "Type == 'zabbix'"
