[hekad]
base_dir="base_heka"
share_dir="/home/mpa/git/mozilla-services/heka/build/heka"

[Dashboard]
type = "DashboardOutput"
address = ":4352"
static_directory = "/home/mpa/git/mozilla-services/heka/build/heka/dasher"
ticker_interval = 5

[tcp:4242]
type = "TcollectorInput"
address = "localhost:4242"
decoder = "tsd_decoder"

[tsd_decoder]
type="OpenTsdbRawDecoder"

[tsd_encoder]
type = "OpenTsdbRawEncoder"

[zabbix_encoder]
type = "ZabbixEncoder"

[OpentsdbZabbixFilter]
strip_tags = [ "product", "cluster", "class" ]
message_matcher = "Type == 'opentsdb'"

# ["match","replace"], ...
replace_tag_name = [ ["/","_"], ["=","-"], ["class_name","cn"], ["exception_class","ec"],
                     ["method_signature","ms"] ]
replace_tag_value = [ ["com.ticketmaster.",""] ]

adaptative_key_shortening = true
adaptative_key_shortening_strategy = "split_value"

  # Increment the ending number to add another rule
  # All replace have been applied by this point
  [OpentsdbZabbixFilter.adaptative_key_shortening_strategy_split_value.1]
  must_match_key = "ms"
  delimiter = "_"
  keep_fields = [ 0 ]
  
[opentsd]
type = "TcpOutput"
address = "127.0.0.1:4243"
encoder = "tsd_encoder"
message_matcher = "Type == 'opentsdb'"

[zabbix]
type = "ZabbixOutput"
encoder = "zabbix_encoder"

ticker_interval = 5
send_key_count = 1000
max_key_count = 2000

#address = "zabbix.tm.tmcs:10051"
#address = "192.168.56.101:10051"
address = "localhost:10051"

# Set to 0 to disable active agent filtering
zabbix_checks_poll_interval=300

key_seen_window = 5

send_timeout = 1000
receive_timeout = 1000

message_matcher = "Type == 'zabbix'"

override_hostname= "jim1.mf.dev43.coresys.tmcs"
